# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
alias render='render.exe'

. "$HOME/.local/bin/env"
export PATH="$PATH:/c/Users/DIPESH/AppData/Local/qwen-code/bin"
